name: Run PR linters

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:

  #
  # golangci-lint runs a suite of static analysis checks on the code
  #

  golangci:
    runs-on: ubuntu-latest
    name: Run golangci-lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: ensure asset generation
        run: go run build.go assets

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          only-new-issues: true

  #
  # Meta checks for formatting, copyright, etc
  #

  correctness:
    name: Check correctness
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Check correctness
        run: |
          go run build.go assets
          go test -v ./meta
