name: Update translations and documentation
on:
  workflow_dispatch:
  schedule:
    - cron: '42 3 * * 1'

jobs:

  update_transifex_docs:
    runs-on: ubuntu-latest
    name: Update translations and documentation
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - uses: actions/setup-go@v4
        with:
          go-version: ^1.19.6
      - run: |
          set -euo pipefail
          git config --global user.name 'Syncthing Release Automation'
          git config --global user.email 'release@syncthing.net'
          bash build.sh translate
          bash build.sh prerelease
          git push
        env:
          WEBLATE_TOKEN: ${{ secrets.WEBLATE_TOKEN }}
